# Generated by Django 5.2.17 on 2026-09-22 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('claims', '0009_f3_receipt_and_observation_targets'),
        ('sources', '0002_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('lifecycle', 'Lifecycle'), ('remittance', 'Remittance')], max_length=20)),
                ('sender_id', models.CharField(max_length=80)),
                ('event_id', models.UUIDField()),
                ('semantic_digest', models.CharField(max_length=64)),
                ('receiver_evidence_fingerprint', models.CharField(max_length=64)),
                ('receiver_receipt_id', models.CharField(max_length=100)),
                ('lifecycle_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('predecessor_event_id', models.UUIDField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(blank=True, max_length=30)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('claim_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.claimrevision')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.deliveryintent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('receiver_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.receiverobservation')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('original_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posting_generation', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_account', to='claims.claimrevision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeBasis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_ordinal', models.PositiveSmallIntegerField()),
                ('original_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('claim_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='claims.claimline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_lines', to='outcomes.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interpreter_version', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('succeeded', models.BooleanField()),
                ('reason_code', models.CharField(max_length=80)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_attempts', to='sources.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InboundCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interpreter_version', models.CharField(max_length=50)),
                ('schema_version', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('lifecycle', 'Lifecycle'), ('remittance', 'Remittance')], max_length=20)),
                ('sender_id', models.CharField(max_length=80)),
                ('event_id', models.UUIDField()),
                ('delivery_key', models.UUIDField()),
                ('intent_id', models.UUIDField()),
                ('claim_revision_id', models.UUIDField()),
                ('receiver_receipt_id', models.CharField(max_length=100)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('lifecycle_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('predecessor_event_id', models.UUIDField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(blank=True, max_length=30)),
                ('normalized_content', models.JSONField()),
                ('semantic_bytes', models.BinaryField()),
                ('semantic_digest', models.CharField(max_length=64)),
                ('interpreted_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_candidates', to='sources.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedEventEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='outcomes.acceptedevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_evidence', to='outcomes.inboundcandidate')),
            ],
        ),
        migrations.AddField(
            model_name='acceptedevent',
            name='primary_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_accepted_events', to='outcomes.inboundcandidate'),
        ),
        migrations.CreateModel(
            name='InboundCandidateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_ordinal', models.PositiveSmallIntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractual_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='outcomes.inboundcandidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InboundConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_conflicting', to='outcomes.inboundcandidate')),
                ('existing_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_existing', to='outcomes.inboundcandidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PostingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_batches', to='outcomes.financialaccount')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posting_batch', to='outcomes.acceptedevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomesCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_uuid', models.UUIDField()),
                ('command_kind', models.CharField(max_length=40)),
                ('target_intent_id', models.UUIDField()),
                ('intent_digest', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('result_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outcomes.acceptedevent')),
                ('target_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outcomes.inboundcandidate')),
                ('result_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outcomes.postingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PostingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payer_reported_payment', 'Payer-reported payment'), ('contractual_adjustment', 'Contractual adjustment')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='outcomes.financialaccount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='outcomes.postingbatch')),
                ('charge_basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='outcomes.chargebasis')),
                ('claim_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.claimline')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outcomes.acceptedevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_account_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('original_charge__gte', 0)), name='out_account_charge_ck'),
        ),
        migrations.AddConstraint(
            model_name='chargebasis',
            constraint=models.UniqueConstraint(fields=('account', 'line_ordinal'), name='out_basis_account_ord_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chargebasis',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_basis_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chargebasis',
            constraint=models.CheckConstraint(condition=models.Q(('original_charge__gte', 0)), name='out_basis_charge_ck'),
        ),
        migrations.AddConstraint(
            model_name='inboundattempt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_inatt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidate',
            constraint=models.UniqueConstraint(fields=('delivery', 'interpreter_version'), name='out_candidate_delivery_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidate',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_candidate_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('kind', 'lifecycle'), ('lifecycle_sequence__isnull', False), ('lifecycle_status__in', ('ACK_ACCEPTED', 'ACK_REJECTED'))), models.Q(('currency', 'USD'), ('kind', 'remittance'), ('lifecycle_sequence__isnull', True), ('lifecycle_status', ''), ('predecessor_event_id__isnull', True)), _connector='OR'), name='out_candidate_kind_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'remittance'), models.Q(('kind', 'lifecycle'), ('lifecycle_sequence__gte', 1)), _connector='OR'), name='out_candidate_lifecycle_sequence_ck'),
        ),
        migrations.AddConstraint(
            model_name='acceptedeventevidence',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_evlink_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='acceptedevent',
            constraint=models.UniqueConstraint(fields=('organization', 'sender_id', 'kind', 'event_id'), name='out_event_semantic_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='acceptedevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'lifecycle')), fields=('organization', 'sender_id', 'intent', 'lifecycle_sequence'), name='out_event_lifecycle_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='acceptedevent',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_event_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidateline',
            constraint=models.UniqueConstraint(fields=('candidate', 'line_ordinal'), name='out_candline_candidate_ord_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidateline',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_candline_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidateline',
            constraint=models.CheckConstraint(condition=models.Q(('line_ordinal__gte', 1), ('line_ordinal__lte', 100)), name='out_candline_ordinal_ck'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidateline',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('contractual_adjustment__gte', 0)), name='out_candline_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='inboundcandidateline',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gt', 0), ('contractual_adjustment__gt', 0), _connector='OR'), name='out_candline_nonzero_ck'),
        ),
        migrations.AddConstraint(
            model_name='inboundconflict',
            constraint=models.UniqueConstraint(fields=('existing_candidate', 'conflicting_candidate', 'reason_code'), name='out_conflict_pair_reason_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundconflict',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_conflict_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='postingbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_batch_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='outcomescommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'request_uuid'), name='out_receipt_org_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='outcomescommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_receipt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='postingentry',
            constraint=models.UniqueConstraint(fields=('event', 'claim_line', 'kind'), name='out_entry_event_line_kind_uniq'),
        ),
        migrations.AddConstraint(
            model_name='postingentry',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='out_entry_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='postingentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='out_entry_amount_positive_ck'),
        ),
    ]
