# Generated by Django 5.2.17 on 2026-09-22 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('records', '0004_f2_service_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('receiver_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('projection_digest', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('lease_owner', models.CharField(max_length=120)),
                ('fencing_generation', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('possible_write', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('initial_queue', 'Initial queue'), ('manual_retry', 'Manual retry')], max_length=20)),
                ('allowed_attempts', models.PositiveSmallIntegerField()),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expected_predecessor_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retry_authorizations', to='archival.archiveattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.AddField(
            model_name='archiveattempt',
            name='authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='archival.archiveauthorization'),
        ),
        migrations.CreateModel(
            name='ArchiveBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_uuid', models.UUIDField()),
                ('command_kind', models.CharField(max_length=40)),
                ('target_key', models.CharField(max_length=200)),
                ('intent_digest', models.CharField(max_length=64)),
                ('result_code', models.CharField(max_length=80)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('result_authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archival.archiveauthorization')),
                ('result_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archival.archivebatch')),
            ],
        ),
        migrations.AddField(
            model_name='archiveauthorization',
            name='command_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='archival.archivecommandreceipt'),
        ),
        migrations.CreateModel(
            name='ArchiveProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=40)),
                ('projection_bytes', models.BinaryField()),
                ('projection_digest', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_projections', to='records.encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('predecessor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='archival.archiveprojection')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archive_head', to='records.encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('projection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='head_for', to='archival.archiveprojection')),
            ],
        ),
        migrations.AddField(
            model_name='archivecommandreceipt',
            name='result_projection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archival.archiveprojection'),
        ),
        migrations.AddField(
            model_name='archiveauthorization',
            name='projection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='archival.archiveprojection'),
        ),
        migrations.AddField(
            model_name='archiveattempt',
            name='projection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='archival.archiveprojection'),
        ),
        migrations.CreateModel(
            name='ArchiveReadbackObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('target_receipt_id', models.CharField(max_length=100)),
                ('reported_organization_id', models.UUIDField()),
                ('reported_encounter_id', models.UUIDField()),
                ('reported_projection_id', models.UUIDField()),
                ('reported_projection_version', models.PositiveIntegerField()),
                ('reported_digest', models.CharField(max_length=64)),
                ('reported_byte_length', models.PositiveIntegerField()),
                ('received_bytes', models.BinaryField()),
                ('evidence_fingerprint', models.CharField(max_length=64)),
                ('observed_state', models.CharField(choices=[('verified', 'Verified'), ('conflict', 'Conflict')], max_length=20)),
                ('conflict_reason', models.CharField(blank=True, max_length=100)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('lookup_projection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readback_observations', to='archival.archiveprojection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readback_observations', to='archival.archiveattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAttemptOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pre_write_failed', 'Pre Write Failed'), ('target_rejected', 'Target Rejected'), ('target_confirmed', 'Target Confirmed'), ('unknown', 'Unknown')], max_length=30)),
                ('reason', models.CharField(max_length=100)),
                ('ended_at', models.DateTimeField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='archival.archiveattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('readback_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_outcomes', to='archival.archivereadbackobservation')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('finished', 'Finished'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('lease_owner', models.CharField(blank=True, max_length=120)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fencing_generation', models.PositiveIntegerField(default=0)),
                ('blocking_reason', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('projection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='archival.archiveprojection')),
                ('scheduled_authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_work', to='archival.archiveauthorization')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archival.archiveauthorization')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='archival.archivebatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archival.archiveprojection')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archival.archivework')),
            ],
        ),
        migrations.AddField(
            model_name='archiveattempt',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='archival.archivework'),
        ),
        migrations.AddConstraint(
            model_name='archivebatch',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_batch_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveprojection',
            constraint=models.UniqueConstraint(fields=('encounter', 'version'), name='arc_projection_enc_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveprojection',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_projection_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveprojection',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='arc_projection_version_ck'),
        ),
        migrations.AddConstraint(
            model_name='archivehead',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_head_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivecommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'request_uuid'), name='arc_receipt_org_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivecommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_receipt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveauthorization',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_auth_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveauthorization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allowed_attempts', 3), ('expected_predecessor_attempt__isnull', True), ('kind', 'initial_queue')), models.Q(('allowed_attempts', 1), ('expected_predecessor_attempt__isnull', False), ('kind', 'manual_retry')), _connector='OR'), name='arc_auth_kind_budget_ck'),
        ),
        migrations.AddConstraint(
            model_name='archivereadbackobservation',
            constraint=models.UniqueConstraint(fields=('receiver_id', 'receiver_version', 'target_receipt_id', 'evidence_fingerprint'), name='arc_observation_receipt_fp_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivereadbackobservation',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_observation_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveattemptoutcome',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_outcome_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivework',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_work_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivebatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'ordinal'), name='arc_item_batch_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivebatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'projection'), name='arc_item_batch_projection_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivebatchitem',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_item_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archivebatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1), ('ordinal__lte', 100)), name='arc_item_ordinal_ck'),
        ),
        migrations.AddConstraint(
            model_name='archiveattempt',
            constraint=models.UniqueConstraint(fields=('authorization', 'ordinal'), name='arc_attempt_auth_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('possible_write', True)), fields=('work', 'fencing_generation'), name='arc_attempt_work_fence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='archiveattempt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='arc_attempt_org_id_uniq'),
        ),
    ]
