# Generated by Django 5.2.17 on 2026-09-13 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('request_uuid', models.UUIDField(default=uuid.uuid4)),
                ('input_digest', models.CharField(max_length=64)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.encounter')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_decisions', to='sources.observation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='records.patient'),
        ),
        migrations.CreateModel(
            name='PatientAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='records.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_patient_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='identitydecision',
            constraint=models.UniqueConstraint(fields=('organization', 'request_uuid'), name='records_decision_org_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='identitydecision',
            constraint=models.UniqueConstraint(fields=('observation',), name='records_decision_observation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='identitydecision',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_decision_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_encounter_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('organization', 'patient', 'id'), name='records_encounter_org_patient_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='patientalias',
            constraint=models.UniqueConstraint(fields=('organization', 'namespace', 'value'), name='records_alias_org_ns_value_uniq'),
        ),
        migrations.AddConstraint(
            model_name='patientalias',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_alias_org_id_uniq'),
        ),
    ]
