# Generated by Django 5.2.17 on 2026-09-22 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('records', '0002_tenant_integrity'),
        ('sources', '0002_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='records.encounter')),
                ('identity_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.identitydecision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('disposition', models.CharField(choices=[('accepted', 'Accepted'), ('excluded', 'Excluded')], max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('units', models.PositiveSmallIntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.encounter')),
                ('evidence_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.observation')),
                ('identity_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.identitydecision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='records.servicerevision')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='records.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_services', to='records.servicerevision'),
        ),
        migrations.CreateModel(
            name='RecordsCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_uuid', models.UUIDField()),
                ('command_kind', models.CharField(max_length=40)),
                ('target_key', models.CharField(max_length=200)),
                ('expected_predecessor_id', models.UUIDField(blank=True, null=True)),
                ('intent_digest', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('result_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.service')),
                ('result_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.servicerevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_srev_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.UniqueConstraint(fields=('organization', 'service', 'id'), name='records_srev_org_service_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.UniqueConstraint(fields=('service', 'revision_number'), name='records_srev_service_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('predecessor__isnull', False)), fields=('predecessor',), name='records_srev_predecessor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='records_srev_number_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 1), ('units__lte', 100)), name='records_srev_units_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='servicerevision',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0)), name='records_srev_amount_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_service_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'encounter', 'patient', 'id'), name='records_service_org_enc_patient_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recordscommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'request_uuid'), name='records_receipt_org_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recordscommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='records_receipt_org_id_uniq'),
        ),
    ]
