# Generated by Django 5.2.17 on 2026-09-22 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('records', '0002_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('policy_version', models.CharField(max_length=40)),
                ('policy_generation', models.PositiveIntegerField()),
                ('route_id', models.CharField(max_length=80)),
                ('route_version', models.CharField(max_length=20)),
                ('envelope_format_version', models.CharField(max_length=20)),
                ('envelope_bytes', models.BinaryField()),
                ('envelope_digest', models.CharField(max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_uuid', models.UUIDField()),
                ('command_kind', models.CharField(max_length=40)),
                ('target_key', models.CharField(max_length=200)),
                ('expected_predecessor_id', models.UUIDField(blank=True, null=True)),
                ('intent_digest', models.CharField(max_length=64)),
                ('result_policy_version', models.CharField(blank=True, max_length=40)),
                ('result_policy_generation', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticPolicySelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
                ('activation_generation', models.PositiveIntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='records.encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envelope_digest', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('units', models.PositiveSmallIntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.claim')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient')),
            ],
        ),
    ]
