# Generated by Django 5.2.17 on 2026-09-22 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('claims', '0001_initial'),
        ('records', '0003_service_servicerevision_service_current_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.service'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='service_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.servicerevision'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.encounter'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.patient'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='claims.claimrevision'),
        ),
        migrations.AddField(
            model_name='claimrevision',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='claims.claimrevision'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='claim_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='claims.claimrevision'),
        ),
        migrations.AddField(
            model_name='claim',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_claims', to='claims.claimrevision'),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization'),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.claimapproval'),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.claim'),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.claimrevision'),
        ),
        migrations.AddField(
            model_name='syntheticpolicyselection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization'),
        ),
        migrations.AddField(
            model_name='syntheticpolicyselection',
            name='selected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_rev_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.UniqueConstraint(fields=('organization', 'claim', 'id'), name='claims_rev_org_claim_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.UniqueConstraint(fields=('claim', 'revision_number'), name='claims_rev_claim_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('predecessor__isnull', False)), fields=('predecessor',), name='claims_rev_predecessor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='claims_rev_number_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.CheckConstraint(condition=models.Q(('policy_generation__gte', 1)), name='claims_rev_policy_generation_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='claimrevision',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='claims_rev_total_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_line_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(fields=('claim_revision', 'ordinal'), name='claims_line_revision_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(fields=('claim_revision', 'service'), name='claims_line_revision_service_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1), ('ordinal__lte', 100)), name='claims_line_ordinal_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('line_amount__gte', 0)), name='claims_line_amount_nonnegative_ck'),
        ),
        migrations.AddConstraint(
            model_name='claimapproval',
            constraint=models.UniqueConstraint(fields=('claim_revision',), name='claims_approval_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimapproval',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_approval_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('organization', 'encounter'), name='claims_case_org_encounter_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_case_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('organization', 'encounter', 'patient', 'id'), name='claims_case_org_enc_patient_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimscommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'request_uuid'), name='claims_receipt_org_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimscommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_receipt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='syntheticpolicyselection',
            constraint=models.UniqueConstraint(fields=('organization',), name='claims_policy_org_uniq'),
        ),
        migrations.AddConstraint(
            model_name='syntheticpolicyselection',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_policy_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='syntheticpolicyselection',
            constraint=models.CheckConstraint(condition=models.Q(('activation_generation__gte', 1)), name='claims_policy_generation_positive_ck'),
        ),
    ]
