# Generated by Django 5.2.17 on 2026-09-22 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('claims', '0003_f2_claim_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_command_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('lease_owner', models.CharField(max_length=120)),
                ('fencing_generation', models.PositiveIntegerField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('route_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('possible_dispatch', models.BooleanField(default=False)),
                ('authorization_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_delivery_attempts', to='claims.claimscommandreceipt')),
                ('effective_authorizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='claims.deliveryattempt'),
        ),
        migrations.CreateModel(
            name='DeliveryIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envelope_digest', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('format_version', models.CharField(max_length=20)),
                ('route_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('delivery_key', models.UUIDField()),
                ('authorized_at', models.DateTimeField()),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_delivery_intents', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_intents', to='claims.claim')),
                ('claim_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_intents', to='claims.claimapproval')),
                ('claim_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_intents', to='claims.claimrevision')),
                ('initial_authorization_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_delivery_intents', to='claims.claimscommandreceipt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='claims.deliveryintent'),
        ),
        migrations.CreateModel(
            name='ClaimDeliveryControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_control', to='claims.claim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('current_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_for_controls', to='claims.deliveryintent')),
            ],
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_delivery_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='claims.deliveryintent'),
        ),
        migrations.CreateModel(
            name='DeliveryWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('blocked', 'Blocked'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('lease_owner', models.CharField(blank=True, max_length=120)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fencing_generation', models.PositiveIntegerField(default=0)),
                ('safe_preflight_failures', models.PositiveSmallIntegerField(default=0)),
                ('blocking_reason', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='claims.deliveryintent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('scheduled_authorization_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_delivery_work', to='claims.claimscommandreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='claims.deliverywork'),
        ),
        migrations.AddField(
            model_name='claimscommandreceipt',
            name='result_delivery_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='claims.deliverywork'),
        ),
        migrations.CreateModel(
            name='ReceiverObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=40)),
                ('receiver_id', models.CharField(max_length=80)),
                ('receiver_version', models.CharField(max_length=20)),
                ('lookup_key', models.UUIDField()),
                ('receipt_id', models.CharField(max_length=100)),
                ('reported_attempt_id', models.UUIDField(blank=True, null=True)),
                ('envelope_digest', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('received_bytes', models.BinaryField(blank=True, null=True)),
                ('observed_state', models.CharField(max_length=20)),
                ('no_acceptance_guaranteed', models.BooleanField(default=False)),
                ('binding_valid', models.BooleanField(default=False)),
                ('conflict_reason', models.CharField(blank=True, max_length=100)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('claim_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.claimrevision')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='claims.deliveryintent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pre_dispatch_failed', 'Pre-dispatch failed'), ('receiver_accepted', 'Receiver accepted'), ('receiver_rejected', 'Receiver rejected'), ('unknown', 'Unknown')], max_length=30)),
                ('reason', models.CharField(max_length=100)),
                ('ended_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='claims.deliveryattempt')),
                ('receiver_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_outcomes', to='claims.receiverobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deliveryintent',
            constraint=models.UniqueConstraint(fields=('organization', 'claim_revision'), name='claims_intent_org_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryintent',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_intent_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryintent',
            constraint=models.UniqueConstraint(fields=('organization', 'claim', 'id'), name='claims_intent_org_claim_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryintent',
            constraint=models.UniqueConstraint(fields=('organization', 'delivery_key'), name='claims_intent_org_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimdeliverycontrol',
            constraint=models.UniqueConstraint(fields=('organization', 'claim'), name='claims_delivery_control_org_claim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='claimdeliverycontrol',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_delivery_control_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliverywork',
            constraint=models.UniqueConstraint(fields=('organization', 'intent'), name='claims_work_org_intent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliverywork',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_work_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('intent', 'ordinal'), name='claims_attempt_intent_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_attempt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('possible_dispatch', True)), fields=('work', 'fencing_generation'), name='claims_attempt_work_fence_dispatch_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiverobservation',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_observation_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attemptoutcome',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='claims_outcome_org_id_uniq'),
        ),
    ]
