# Generated by Django 5.2.17 on 2026-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_f3_delivery_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverobservation',
            name='evidence_fingerprint',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_byte_length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_claim_revision_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_delivery_key',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_envelope_digest',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_intent_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_organization_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_receiver_id',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='receiverobservation',
            name='reported_receiver_version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
