# Generated by Django 5.2.17 on 2026-09-13 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_length', models.PositiveIntegerField()),
                ('media_type', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_namespace', models.CharField(max_length=100)),
                ('source_key', models.CharField(max_length=200)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.artifact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='ParseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('succeeded', models.BooleanField()),
                ('reason_code', models.CharField(max_length=80)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(max_length=50)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_ordinal', models.PositiveIntegerField()),
                ('raw_values', models.JSONField()),
                ('normalized_values', models.JSONField()),
                ('warnings', models.JSONField(default=list)),
                ('source_locator', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access.organization')),
                ('parse_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='sources.parseresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('organization', 'sha256'), name='sources_artifact_org_sha_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='sources_artifact_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('organization', 'source_namespace', 'source_key'), name='sources_delivery_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='sources_delivery_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parseattempt',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='sources_attempt_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parseresult',
            constraint=models.UniqueConstraint(fields=('delivery', 'parser_version'), name='sources_result_delivery_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parseresult',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='sources_result_org_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('parse_result', 'row_ordinal'), name='sources_observation_result_row_uniq'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='sources_observation_org_id_uniq'),
        ),
    ]
